version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/01/master.conf:/usr/local/etc/redis/redis.conf"
    command: "redis-server --include /usr/local/etc/redis/redis.conf"
  redis-slave1:
    container_name: "slave1"
    image: redis
    ports:
      - "6380:6379"
    command: "redis-server --include /usr/local/etc/redis/redis.conf"
    volumes:
      - "./data/02/slave.conf:/usr/local/etc/redis/redis.conf"
  redis-slave2:
    container_name: "slave2"
    image: redis
    ports:
      - "6381:6379"
    command: "redis-server --include /usr/local/etc/redis/redis.conf"
    volumes:
      - "./data/02/slave.conf:/usr/local/etc/redis/redis.conf"