spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 26379
    sentinel:
      master: mymaster
      nodes:
        - 127.0.0.1:26379
        - 127.0.0.1:26380
        - 127.0.0.1:26381
    lettuce:
      shutdown-timeout: 200ms